name: Docker build images

# Controls when the action will run.
on: [ push, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        name: ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: [ sofabuilder_ubuntu, sofabuilder_centos ]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout source code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set DOCKERHUB_IMAGE_TAG
            run: |
                DOCKERHUB_IMAGE_TAG="${GITHUB_REF#refs/heads/}"
                echo "DOCKERHUB_IMAGE_TAG = $DOCKERHUB_IMAGE_TAG"
                if [ -z "$DOCKERHUB_IMAGE_TAG" ]; then exit 1; fi
                echo "DOCKERHUB_IMAGE_TAG=$DOCKERHUB_IMAGE_TAG" >> $GITHUB_ENV

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: docker/${{ matrix.target }} # path of the Dockerfile
                push: true
                tags: sofaframework/${{ matrix.target }}:${{ env.DOCKERHUB_IMAGE_TAG }}
