name: Update SOFA binaries

# Controls when the action will run.
on:
    workflow_dispatch:
        inputs:
            binaries_branch:
                description: 'binaries_branch'
                required: true
                default: 'v20.12'
            binaries_config:
                description: 'binaries_config'
                required: true
                default: 'standard'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        name: ${{ matrix.target }}/${{ github.event.inputs.binaries_config }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: [ sofa_nightly_ubuntu ]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout source code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: docker/${{ matrix.target }} # path of the Dockerfile
                build-args: |
                    BINARIES_BRANCH=${{ github.event.inputs.binaries_branch }}
                    BINARIES_CONFIG=${{ github.event.inputs.binaries_config }}
                push: true
                tags: sofaframework/${{ matrix.target }}:${{ github.event.inputs.binaries_branch }}-${{ github.event.inputs.binaries_config }}
