name: Push image with latest SOFA binaries

# Controls when the action will run.
on:
    workflow_dispatch:
        inputs:
            matrix_configs:
                description: 'Configs to set in the matrix'
                required: false
                default: "[ minimal, standard, full ]"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        name: ${{ matrix.target }}/${{ matrix.config }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: [ sofa_nightly_ubuntu ]
                config: ${{ github.event.inputs.matrix_configs }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout source code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: docker/${{ matrix.target }} # path of the Dockerfile
                build-args: |
                    BINARIES_CONFIG=${{ matrix.config }}
                push: true
                tags: sofaframework/${{ matrix.target }}:${{ matrix.config }}
